version: 2.0

jobs:
  oldcam:
    docker:
      - image: z4nyx/docker:latest
    steps:
      - run: git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
      - run: cp -af sources.list /etc/apt/
      - run: cp -af 99own /etc/apt/apt.conf.d/
      - run: apt update && apt upgrade -y
      - run: ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
      - run: apt install -f -y libxml2 libssl-dev default-jre python3 python3-pip
      - run: bash build.sh --old

  newcam:
    docker:
      - image: z4nyx/docker:latest
    steps:
      - run: git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
      - run: cp -af sources.list /etc/apt/
      - run: cp -af 99own /etc/apt/apt.conf.d/
      - run: apt update && apt upgrade -y
      - run: ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
      - run: apt install -f -y libxml2 libssl-dev default-jre python3 python3-pip
      - run: bash build.sh --new

  qti:
    docker:
      - image: z4nyx/docker:latest
    steps:
      - run: git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
      - run: cp -af sources.list /etc/apt/
      - run: cp -af 99own /etc/apt/apt.conf.d/
      - run: apt update && apt upgrade -y
      - run: ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
      - run: apt install -f -y libxml2 libssl-dev default-jre python3 python3-pip
      - run: git apply QTI_HAPTICS.p
      - run: bash build.sh --qti

workflows:
  version: 2
  build:
    jobs:
      - oldcam
      - newcam
      - qti
